name: pyconference-pretalx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.3
  - jupyterlab=3.3
  - openpyxl=3.0
  - ca-certificates
  - openssl
  - pip=22
  - omegaconf=2.1
  - requests=2
  # logging
  - structlog=21.5
  # for coloring console logs
  - colorama
  # if dropbox is used for sync:
  - dropbox
