# Configuration for Project = Conference

# Project name, same as directory
name: my-conference

# Event name in pretalx
pretalx_event_slug: my-conference-slug

# Conference Settings
conference_name: "My Conference"
program_email: "program22@myconference.org"

# Setup
# path to private stuff as tokens
private_path: "_private"
# path to store raw data not to be shared
data_path: "_data"
# path to store data publicly
public_path: "public"

# path to pretalx data and processed data
submissions:
  json: "submissions.json"
  raw_json: "submissions_raw.json"
  path: ${data_path}/${submissions.json}
  raw_path: ${data_path}/${submissions.raw_json}
  public_path: ${public_path}/${submissions.json}
speakers:
  json: "speakers.json"
  raw_json: "speakers_raw.json"
  path: ${data_path}/${speakers.json}
  raw_path: ${data_path}/${speakers.raw_json}
  public_path: ${public_path}/${speakers.json}
schedule:
  json: "schedule.json"
  raw_json: "schedule_raw.json"
  path: ${data_path}/${schedule.json}
  raw_path: ${data_path}/${speakers.raw_json}
  public_path: ${public_path}/${schedule.json}


# Pretalx Basics
pretalx:
  base_url: "https://pretalx.com"
  token: unset
  token_dir: ${private_path}
  token_file_name: TOKEN.txt
  # language to read in, pretalx supports multiple, we only handle one here
  langauge: en
