# Configuration for Project = Conference

# Project name, same as directory
name: my-conference

# Event name in pretalx
pretalx_event_slug: my-conference-slug

# Conference Settings
conference_name: "My Conference"
program_email: "program22@myconference.org"

# Setup
# path to private stuff as tokens
private_path: "_private"
# path to store raw data not to be shared
data_path: "_data"
# path to store data publicly
public_path: "public"

# path to pretalx data and processed data for each section
submissions:
  api_section: true
  endpoint: submissions
  json: ${submissions.endpoint}.json
  raw_json: ${submissions.endpoint}_raw.json
  path: ${data_path}/${submissions.json}
  raw_path: ${data_path}/${submissions.raw_json}
  public_path: ${public_path}/${submissions.json}
speakers:
  api_section: true
  endpoint: speakers
  json: ${speakers.endpoint}.json
  raw_json: ${speakers.endpoint}_raw.json
  path: ${data_path}/${speakers.json}
  raw_path: ${data_path}/${speakers.raw_json}
  public_path: ${public_path}/${speakers.json}
schedule:
  api_section: true
  endpoint: schedule
  json: ${schedule.endpoint}.json
  raw_json: ${schedule.endpoint}_raw.json
  path: ${data_path}/${schedule.json}
  raw_path: ${data_path}/${speakers.raw_json}
  public_path: ${public_path}/${schedule.json}
answers:
  api_section: true
  endpoint: answers
  json: ${answers.endpoint}.json
  raw_json: ${answers.endpoint}_raw.json
  path: ${data_path}/${answers.json}
  raw_path: ${data_path}/${answers.raw_json}
  public_path: ${public_path}/${answers.json}
questions:
  api_section: true
  endpoint: questions
  json: ${questions.endpoint}.json
  raw_json: ${questions.endpoint}_raw.json
  path: ${data_path}/${questions.json}
  raw_path: ${data_path}/${questions.raw_json}
  public_path: ${public_path}/${questions.json}


# Pretalx Basics
pretalx:
  base_url: "https://pretalx.com"
  token: unset
  token_dir: ${private_path}
  token_file_name: TOKEN.txt
  # language to read in, pretalx supports multiple, we only handle one here
  language: en
  # states relevant for speaking
  confirmed_accepted:
    - confirmed
    - accepted
  confirmed: confirmed
  accepted: accepted
