# Configuration for Project = Conference

# Project name, same as directory
name: europython-2022

# Event name in pretalx
pretalx_event_slug: europython-2022

# Conference Settings
conference_name: "EuroPython 2022"
program_addy: program-wg@europython.eu
