# Configuration for Project = Conference

# Project name, same as directory
name: europython-2022

# Event name in pretalx
pretalx_event_slug: europython-2022

# Conference Settings
conference_name: "PyConDE & PyData Berlin"
program_addy: program22@pycon.de

