# Configuration for Project = Conference

# Project name, same as directory
name: my-conference

# Event slug in pretalx
pretalx_event_slug: my-conference-slug

# Conference Settings
conference_name: "My Conference 3000"
program_addy: programg@myconference.eu


pretalx:
  questions:
    # list all relevant nodes for processing questions here
    select_nodes:
      - question
      - id
      - contains_personal_data
      - options